version: 2

jobs:
  test:
    working_directory: ~/build
    docker:
    - image: circleci/node
    steps:
    - checkout
    - restore_cache:
        key: api-cache-{{ checksum "./package.json" }}
    - run:
        name: install deps
        command: make install
    - save_cache:
        key: api-cache-{{ checksum "./package.json" }}
        paths:
          - ./node_modules
    - run:
        name: test
        command: make test

workflows:
  version: 2
  development:
    jobs:
      - test
